### ISSUE TITLE
In/out for states not working properly

### ISSUE THREAD

**Issue by TheFes** [home-assistant/intents#1004]
Test case (nl)

intents:
```yaml
language: nl
intents:
  HassGetState:
    data:
      - sentences:
          - Wat is de [status van] <name> [in <area>]
        response: one

      - sentences:
          - (Is|Staat) [de status van] <name> {on_off_states:state} [in <area>]
        response: one_yesno
        excludes_context:
          domain:
            - cover
```
responses:
```yaml
language: nl
responses:
  intents:
    HassGetState:
      one: |
        {{ slots.name | capitalize }} is {{ state.state_with_unit }}
      one_yesno: |
        {% if query.matched: %}
          Ja
        {% else: %}
          Nee, die is {{ state.state_with_unit }}
        {% endif %}
```

fixture:
```yaml
entities:
  - name: Slaapkamerlamp
    id: light.slaapkamer_lamp
    area: slaapkamer
    state:
      in: "uit"
      out: "off"
```

common:
```yaml
  on_off_states:
    values:
      - in: "aan"
        out: "on"
      - in: "uit"
        out: "off"
 ```

Tests:
```
@TheFes ➜ /workspaces/intents (main) $ python3 -m script.intentfest parse --language nl --sentence 'staat slaapkamerlamp uit'
{
  "text": "staat slaapkamerlamp uit",
  "match": true,
  "intent": "HassGetState",
  "slots": {
    "name": "Slaapkamerlamp",
    "state": "off"
  },
  "response_key": "one_yesno",
  "response": "Nee, die is uit"
```
Expected result was `"Ja"`

```
@TheFes ➜ /workspaces/intents (main) $ python3 -m script.intentfest parse --language nl --sentence 'wat is de status van slaapkamerlamp'
{
  "text": "wat is de status van slaapkamerlamp",
  "match": true,
  "intent": "HassGetState",
  "slots": {
    "name": "Slaapkamerlamp"
  },
  "response_key": "one",
  "response": "Slaapkamerlamp is uit"
```
This is indeed the expected result

So the intents checking on a state are now working anymore now
