### ISSUE TITLE
Spaces are ignored for Dutch intents

### ISSUE THREAD

**Issue by TheFes** [home-assistant/intents#1021]
Possible also for others (but not for EN)

```json
@TheFes ➜ /workspaces/intents (nl_add_stuff) $ python3 -m script.intentfest parse --language nl --sentence 'allekeukenverlichtinguit'
{
  "text": "allekeukenverlichtinguit",
  "match": true,
  "intent": "HassTurnOff",
  "slots": {
    "area": "Keuken",
    "domain": "light",
    "name": "all"
  },
  "response_key": "lights_area",
  "response": "De lampen in keuken zijn uitgezet"
```

Matching intent:
```yaml
intents:
  HassTurnOff:
    data:
      - sentences:
          - "[<doe>|<zou>] (alle|in) <area>[ ]<lamp> [<naar>] uit [willen|kunnen] [<doe>]"
        response: "lights_area"
        slots:
          domain: "light"
          name: "all"
 ```
