### ISSUE TITLE
light_HassTurnOn individual light - expected/unexpected slot "domain"

### ISSUE THREAD

**Issue by tetele** [home-assistant/intents#1068]
I need different responses for HassTurnOn for the light domain, because the (most common) wording for turning on lights is different in Romanian than for turning on switches or other things. Obviously, I need exclusion rules (`excludes_context: { domain: light }`) for the `homeassistant_HassTurnOn` domain.

However, that doesn't seem to be possible to achieve.

`sentences/ro/light_HassTurnOn.yaml`
```
language: ro
intents:
  HassTurnOn:
    data:
      - sentences:
          - "<porneste> <name>"
        requires_context:
          domain: light
        response: light # defined with different wording in responses
```

`tests/ro/light_HassTurnOn.yaml`
```
language: ro
tests:
  - sentences:
      - "aprinde plafoniera neagra"
    intent:
      name: HassTurnOn
      slots:
        name: plafoniera neagra
        domain: light # here's the issue
    response: "Am aprins plafoniera neagra"
```
====================================== short test summary info =======================================
FAILED tests/test_language_sentences.py::test_light_HassTurnOn[ro] - AssertionError: Slot domain was not expected for: aprinde plafoniera neagra
==================================== 1 failed, 26 passed in 0.65s ====================================
```

I get this error:

```

If i delete the `domain: light` line in the test file, I get
```
====================================== short test summary info =======================================
FAILED tests/test_language_sentences.py::test_light_HassTurnOn[ro] - AssertionError: File light_HassTurnOn: tests should have domain slot set to light
==================================== 1 failed, 26 passed in 0.69s ====================================
```
