### ISSUE TITLE
Plural word support.

### ISSUE THREAD

**Issue by ernst77** [home-assistant/intents#1079]
As we are moving on with responses would be nice to have plural word support.

It's easy for english language as you only have two forms (e.g. `device` and `devices`) some languages have 3 forms for different amounts (e.g. Lithuanian 1 - `įrenginys`, 2-`įrenginiai`, 3-`įrenginių`) some even 5(or 6?).

Would there be a possibility for example to specify `variable name` and `count` and correct form would be given. 

I've had experience with https://www.i18next.com/translation-function/plurals their system seems to work fine for plurals on different languages. Maybe we could get an inspiration from them? :D

**Comment by AalianKhan** [comment]
Hey
I am a bit confused about why. 
if we implement this, what will it enable us to do?

**Comment by tetele** [comment]
I would suggest an option similar to `requires_context`, maybe called `requires_cardinality`, which only recognizes the intent if the matched set of entities has the exact required cardinality. The reasoning for my suggestion is that it can be applied in multiple circumstances, but the main one I can think of is for when asking about the state of "all" devices in an area, where "all"=1.

Specifically: "is the kitchen light on?" is basically the same as "are the kitchen lights on?" when the kitchen has exactly one light. However, when there are 2 lights, "are the kitchen lights on?" has a deterministic answer, whereas "is the kitchen light on?" begs the question "which light?" instead of "sorry, i didn't understand".

Here's a demo snippet of my proposal:
`responses/HassGetState.yaml`
```
responses:
  intents:
    HassGetState:

      all: |
        {% if not query.unmatched: %}
          Yes
        {% else %}
          {% set no_match = query.unmatched | map(attribute="name") | sort | list %}
          {% if no_match | length > 4 %}
            No, {{ no_match[:3] | join(", ") }} and {{ (no_match | length - 3) }} more not
          {%- else -%}
            No,
            {% for name in no_match -%}
              {% if not loop.first and not loop.last %}, {% elif loop.last and not loop.first %} and {% endif -%}
              {{ name }}
            {%- endfor %} not
          {% endif %}
        {% endif %}

      all_one: |
        There's just one {{ slots.domain }} and it's {{ state.state_with_unit }}
```

`sentences/HassGetState.yaml`
```
intents:
  HassGetState:
    data:
      - sentences:
          - are all [the] {on_off_domains:domain} {on_off_states:state} [in <area>]
        response: all
        requires_cardinality:
          above: 1
      - sentences:
          - are all [the] {on_off_domains:domain} {on_off_states:state} [in <area>]
        response: all_one
        requires_cardinality:
          exactly: 1
      - sentences:
          - is [the] {on_off_domains:domain} {on_off_states:state} [in <area>]
        response: all
        requires_cardinality:
          exactly: 1
```
