### ISSUE TITLE
Matching device class

### ISSUE THREAD

**Issue by spuljko** [home-assistant/intents#1244]
When there is device class in sentence intent slot results are not as expected. For example (I know there is already this sentence in code, but this is just for testing purposes)
```
      - sentences:
          - "how many {cover_classes:device_class} (is|are) {cover_states:state} [in <area>]"
        response: how_many
        slots:
          domain: cover
          device_class:
            - curtain
            - blind
```
Test sentence:
```
  - sentences:
      - "how many curtains are closed?"
    intent:
      name: HassGetState
      slots:
        domain: cover
        device_class: curtain
        state: "closed"
    response: "2"
```
Expected result is 2, but assert fails with '0' in {'2'}

Similar thing happens if I try to query temperature sensor:
```
      - sentences:
          - "what is [the] {sensor_classes:device_class} [in <area>]"
        response: one
        slots:
          domain: sensor
          device_class:
            - temperature
            - humidity
```
Test sentences:
```
  - sentences:
      - "what is the temperature in the living room?"
    intent:
      name: HassGetState
      slots:
        domain: sensor
        device_class: temperature
    response: "20 °C"

  - sentences:
      - "what is the humidity in the living room?"
    intent:
      name: HassGetState
      slots:
        domain: sensor
        device_class: humidity
    response: "60 %"
```
query.matched is 0, although there are sensors in fixtures.
