### ISSUE TITLE
Tests should check if response has all the required slots

### ISSUE THREAD

**Issue by thdg** [home-assistant/intents#1256]
Tests can pass but running script.intentfest parse will produce an error if the response includes a slot that is not required for the intent.

Example:

Sentence is `"Turn on all the lights in the living room"` [translated]
Response is `"Turned on {{ slots.name }}"` [translated]

All tests pass.

Running `python3 -m script.intentfest parse --language is --sentence "Turn on all the lights in the living room" [translated]` produces the error:
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'name' _(slots["name"] does not exist)_

Suggestion:

Tests should verify if a response will be rendered without errors.

**Comment by thdg** [comment]
Maybe this was always possible, but adding `response: <your-response>` to the test will test the response.
Example:
```
  - sentences:
      - "Turn on all the lights in the living room"
    intent:
      name: HassTurnOn
      slots:
        area: Living room
    response: "Turned on {{ slots.name }}"
```
