### ISSUE TITLE
Assist not picking up get temperature in area intent

### ISSUE THREAD

**Issue by blacknell** [home-assistant/intents#1351]
I've asked `what is the temperature in the bathroom` and it comes back with `Temperature is`

But asking `what is the bathroom temperature` works with `Bathroom temperature is 17.9 °C`

The problematic question pipeline seems to pick up the domain and area correctly but not the entity. 
I've looked through the sentences and can't be sure which it is using `HassGetState` or `HassClimateGetTemperature`

### Problematic language processing
```
intent_output:
  response:
    speech:
      plain:
        speech: Temperature is
        extra_data: null
    card: {}
    language: en
    response_type: query_answer
    data:
      targets: []
      success:
        - name: Bathroom
          type: area
          id: bathroom
      failed: []
  conversation_id: null
```

### Problematic Raw
```
init_options:
  start_stage: intent
  end_stage: intent
  input:
    text: what is the temperature in the bathroom
  pipeline: 01gzmc9kyd6gjsg3e79ne8nekd
  conversation_id: null
stage: done
run:
  pipeline: 01gzmc9kyd6gjsg3e79ne8nekd
  language: en
  runner_data:
    stt_binary_handler_id: null
    timeout: 30
events:
  - type: run-start
    data:
      pipeline: 01gzmc9kyd6gjsg3e79ne8nekd
      language: en
      runner_data:
        stt_binary_handler_id: null
        timeout: 30
    timestamp: "2023-05-05T08:04:14.368342+00:00"
  - type: intent-start
    data:
      engine: homeassistant
      language: en
      intent_input: what is the temperature in the bathroom
    timestamp: "2023-05-05T08:04:14.368798+00:00"
  - type: intent-end
    data:
      intent_output:
        response:
          speech:
            plain:
              speech: Temperature is
              extra_data: null
          card: {}
          language: en
          response_type: query_answer
          data:
            targets: []
            success:
              - name: Bathroom
                type: area
                id: bathroom
            failed: []
        conversation_id: null
    timestamp: "2023-05-05T08:04:14.405445+00:00"
  - type: run-end
    data: null
    timestamp: "2023-05-05T08:04:14.405673+00:00"
intent:
  engine: homeassistant
  language: en
  intent_input: what is the temperature in the bathroom
  done: true
  intent_output:
    response:
      speech:
        plain:
          speech: Temperature is
          extra_data: null
      card: {}
      language: en
      response_type: query_answer
      data:
        targets: []
        success:
          - name: Bathroom
            type: area
            id: bathroom
        failed: []
    conversation_id: null
```

### Successful language processing
```
intent_output:
  response:
    speech:
      plain:
        speech: Bathroom temperature is 17.9 °C
        extra_data: null
    card: {}
    language: en
    response_type: query_answer
    data:
      targets: []
      success:
        - name: Bathroom Temperature
          type: entity
          id: sensor.temphumid_bathroom_temperature
      failed: []
  conversation_id: null

```

**Comment by OzGav** [comment]
I am seeing similar:
```
What is the temperature in abigail's bedroom
Sorry, I couldn't understand that
What is Abigail's bedroom temperature?
Abigail's bedroom temperature is 17.34 °C
```
However, my raw shows an intent match failure:
```
stage: done
run:
  pipeline: 01gzhtprzzc4rkgr276g0ykwr4
  language: en
  runner_data:
    stt_binary_handler_id: null
    timeout: 30
events:
  - type: run-start
    data:
      pipeline: 01gzhtprzzc4rkgr276g0ykwr4
      language: en
      runner_data:
        stt_binary_handler_id: null
        timeout: 30
    timestamp: "2023-05-08T23:01:10.691293+00:00"
  - type: intent-start
    data:
      engine: homeassistant
      language: en
      intent_input: What is the temperature in abigail's bedroom
    timestamp: "2023-05-08T23:01:10.691638+00:00"
  - type: intent-end
    data:
      intent_output:
        response:
          speech:
            plain:
              speech: Sorry, I couldn't understand that
              extra_data: null
          card: {}
          language: en
          response_type: error
          data:
            code: no_intent_match
        conversation_id: null
    timestamp: "2023-05-08T23:01:10.797547+00:00"
  - type: run-end
    data: null
    timestamp: "2023-05-08T23:01:10.797721+00:00"
intent:
  engine: homeassistant
  language: en
  intent_input: What is the temperature in abigail's bedroom
  done: true
  intent_output:
    response:
      speech:
        plain:
          speech: Sorry, I couldn't understand that
          extra_data: null
      card: {}
      language: en
      response_type: error
      data:
        code: no_intent_match
    conversation_id: null
```
