### ISSUE TITLE
Assist fails to understand when an apostrophe is in the entity name

### ISSUE THREAD

**Issue by OzGav** [home-assistant/intents#1353]
When asking assist for the state of a room which has an apostrophe in the entity name the request fails. Using an alias without the apostrophe succeeds. The below is actual text from intially a spoken request and then a typed question

```
What is the state of Abigail's window?
Sorry, I couldn't understand that
What is the state of Abigails window?
Abigails window is off
```

**Comment by tetele** [comment]
Both HassIL and the intents engine properly recognize and interpret apostrophes in sentences and fixture names as far as my tests go. In Home assistant there are no apostrophes in supported intents in English at the moment, the only accepted question for HassGetState being `(do you know|tell me|what is) [the state of] <name> [in <area>]` - note the lack of "what's". That's an oversight, but it does work as expected.

I have also tested with HA 2023.5.2 and my entities containing apostrophes seem to work well.

```yaml
init_options:
  start_stage: intent
  end_stage: intent
  input:
    text: what is the state of karla's room window?
  pipeline: 01gzhmqejg8bk74dwjy1dpry18
  conversation_id: null
stage: done
run:
  pipeline: 01gzhmqejg8bk74dwjy1dpry18
  language: en
  runner_data:
    stt_binary_handler_id: null
    timeout: 30
events:
  - type: run-start
    data:
      pipeline: 01gzhmqejg8bk74dwjy1dpry18
      language: en
      runner_data:
        stt_binary_handler_id: null
        timeout: 30
    timestamp: "2023-05-08T07:12:10.039537+00:00"
  - type: intent-start
    data:
      engine: homeassistant
      language: en
      intent_input: what is the state of karla's room window?
    timestamp: "2023-05-08T07:12:10.039577+00:00"
  - type: intent-end
    data:
      intent_output:
        response:
          speech:
            plain:
              speech: Karla's room window is off
              extra_data: null
          card: {}
          language: en
          response_type: query_answer
          data:
            targets: []
            success:
              - name: Karla's room window
                type: entity
                id: binary_sensor.karlas_room_window
            failed: []
        conversation_id: null
    timestamp: "2023-05-08T07:12:10.049988+00:00"
  - type: run-end
    data: null
    timestamp: "2023-05-08T07:12:10.050088+00:00"
intent:
  engine: homeassistant
  language: en
  intent_input: what is the state of karla's room window?
  done: true
  intent_output:
    response:
      speech:
        plain:
          speech: Karla's room window is off
          extra_data: null
      card: {}
      language: en
      response_type: query_answer
      data:
        targets: []
        success:
          - name: Karla's room window
            type: entity
            id: binary_sensor.karlas_room_window
        failed: []
    conversation_id: null

```

@OzGav could you please use [the debug feature](https://www.home-assistant.io/docs/assist/troubleshooting/) on the voice/text pipeline and get back with some extra info, like the raw ? Are you sure that's your entity's name?

**Comment by OzGav** [comment]
Thanks @tetele here is the raw
```
stage: done
run:
  pipeline: 01gzhtprzzc4rkgr276g0ykwr4
  language: en
  runner_data:
    stt_binary_handler_id: 4
    timeout: 30
events:
  - type: run-start
    data:
      pipeline: 01gzhtprzzc4rkgr276g0ykwr4
      language: en
      runner_data:
        stt_binary_handler_id: 4
        timeout: 30
    timestamp: "2023-05-08T13:23:50.552253+00:00"
  - type: stt-start
    data:
      engine: cloud
      metadata:
        language: en-AU
        format: wav
        codec: pcm
        bit_rate: 16
        sample_rate: 16000
        channel: 1
    timestamp: "2023-05-08T13:23:50.553066+00:00"
  - type: stt-end
    data:
      stt_output:
        text: What is the state of Abigail's window?
    timestamp: "2023-05-08T13:23:58.752420+00:00"
  - type: intent-start
    data:
      engine: homeassistant
      language: en
      intent_input: What is the state of Abigail's window?
    timestamp: "2023-05-08T13:23:58.752608+00:00"
  - type: intent-end
    data:
      intent_output:
        response:
          speech:
            plain:
              speech: Sorry, I couldn't understand that
              extra_data: null
          card: {}
          language: en
          response_type: error
          data:
            code: no_intent_match
        conversation_id: null
    timestamp: "2023-05-08T13:23:58.835398+00:00"
  - type: tts-start
    data:
      engine: cloud
      language: en-AU
      voice: WilliamNeural
      tts_input: Sorry, I couldn't understand that
    timestamp: "2023-05-08T13:23:58.835589+00:00"
  - type: tts-end
    data:
      tts_output:
        media_id: >-
          media-source://tts/cloud?message=Sorry,+I+couldn't+understand+that&language=en-AU&voice=WilliamNeural
        url: >-
          /api/tts_proxy/dae2cdcb27a1d1c3b07ba2c7db91480f9d4bfd8f_en-au_ac9954e3d7_cloud.audiooutput.mp3
        mime_type: audio/mpeg
    timestamp: "2023-05-08T13:23:58.837026+00:00"
  - type: run-end
    data: null
    timestamp: "2023-05-08T13:23:58.837158+00:00"
stt:
  engine: cloud
  metadata:
    language: en-AU
    format: wav
    codec: pcm
    bit_rate: 16
    sample_rate: 16000
    channel: 1
  done: true
  stt_output:
    text: What is the state of Abigail's window?
intent:
  engine: homeassistant
  language: en
  intent_input: What is the state of Abigail's window?
  done: true
  intent_output:
    response:
      speech:
        plain:
          speech: Sorry, I couldn't understand that
          extra_data: null
      card: {}
      language: en
      response_type: error
      data:
        code: no_intent_match
    conversation_id: null
tts:
  engine: cloud
  language: en-AU
  voice: WilliamNeural
  tts_input: Sorry, I couldn't understand that
  done: true
  tts_output:
    media_id: >-
      media-source://tts/cloud?message=Sorry,+I+couldn't+understand+that&language=en-AU&voice=WilliamNeural
    url: >-
      /api/tts_proxy/dae2cdcb27a1d1c3b07ba2c7db91480f9d4bfd8f_en-au_ac9954e3d7_cloud.audiooutput.mp3
    mime_type: audio/mpeg
```

Here is the entity info:
![image](https://user-images.githubusercontent.com/19848947/236836238-14b2ecc0-cf40-4edd-9021-d55cdaca0314.png)

Here is the raw when I type in the request without the apostrophe:

```
stage: done
run:
  pipeline: 01gzhtprzzc4rkgr276g0ykwr4
  language: en
  runner_data:
    stt_binary_handler_id: null
    timeout: 30
events:
  - type: run-start
    data:
      pipeline: 01gzhtprzzc4rkgr276g0ykwr4
      language: en
      runner_data:
        stt_binary_handler_id: null
        timeout: 30
    timestamp: "2023-05-08T13:26:31.772688+00:00"
  - type: intent-start
    data:
      engine: homeassistant
      language: en
      intent_input: What is the state of Abigails window?
    timestamp: "2023-05-08T13:26:31.772911+00:00"
  - type: intent-end
    data:
      intent_output:
        response:
          speech:
            plain:
              speech: Abigails window is off
              extra_data: null
          card: {}
          language: en
          response_type: query_answer
          data:
            targets: []
            success:
              - name: Abigail’s Window
                type: entity
                id: binary_sensor.abigail_window_contact
            failed: []
        conversation_id: null
    timestamp: "2023-05-08T13:26:31.883752+00:00"
  - type: run-end
    data: null
    timestamp: "2023-05-08T13:26:31.883968+00:00"
intent:
  engine: homeassistant
  language: en
  intent_input: What is the state of Abigails window?
  done: true
  intent_output:
    response:
      speech:
        plain:
          speech: Abigails window is off
          extra_data: null
      card: {}
      language: en
      response_type: query_answer
      data:
        targets: []
        success:
          - name: Abigail’s Window
            type: entity
            id: binary_sensor.abigail_window_contact
        failed: []
    conversation_id: null
```
