### ISSUE TITLE
Changing sentence trigger response text

### ISSUE THREAD

**Issue by zolakt** [home-assistant/intents#1450]
Hi, sorry if this has already been asked, but I've searched for it extensively and couldn't find a thing.

I'm using the new sentence trigger in automations. In my case I'm using node-red, but I assume the issue is the same with ha automations.

I'm using it in Croatian. The speech to text works fine. The trigger works fine. The automation gets executed. And then the assistant replies with "Done", even though I'm using Croatian. When pronounced in Croatian this sounds weird. I know you support custom response texts, but those are for named intents like HassGetState/HassTurnOn/etc. 

So, is there any way I can change the "Done" response?
Ideally, I'd like to have different responses for different triggers, and possibly multiple responses for each triggers, so it picks one randomly.

![image](https://github.com/home-assistant/intents/assets/1048531/8525b28b-286a-4257-a3ba-a834f12d8bb3)

**Comment by tonka3000** [comment]
I have the same issue with German. Would love to be able to set a custom response or at least a translated default response.

**Comment by sanyatuning** [comment]
You can create custom intent which may has custom reply.
See here: https://www.home-assistant.io/voice_control/custom_sentences/#setting-up-custom-sentences-in-configurationyaml

**Comment by tetele** [comment]
Yes, but you can't set the response text for sentence triggers (or even change its language), which is what this (valid) issue is about :)

Custom intents are not some well kept secret, they're just harder to use for the average user, accustomed to fiddle with stuff in the UI and without requiring a restart.

**Comment by sanyatuning** [comment]
You can have custom reply ![Screenshot_2023-10-17-08-27-59-968_io.homeassistant.companion.android.jpg](https://github.com/home-assistant/intents/assets/2077907/f08f2933-608c-4627-86b0-f23598ad815c)

**Comment by tetele** [comment]
Yes, but not for sentence triggers
![sentence trigger](https://github.com/home-assistant/intents/assets/920098/8dab6d39-b194-4943-a119-06599b1e4f2e)

**Comment by TheFes** [comment]
It would be nice if Assist would pick up things like this in an automation:
(even nicer if you don't have to provide the entire dict as variable, but I copied it from an actual response from the get conversation service call)
```yaml
alias: TEST RESPONSE
trigger:
  - platform: conversation
    command: something something
action:
  - variables:
      assist_response:
        response:
          speech:
            plain:
              speech: Testing 123
        language: en
        response_type: action_done
  - stop: Return response
    response_variable: assist_response
mode: single
```
