### ISSUE TITLE
Wildcard recognition fails when a certain expansion rule is used

### ISSUE THREAD

**Issue by tetele** [home-assistant/intents#1479]
I have the following defined in Romanian:

`sentences/ro/shopping_list_HassShoppingListAddItem.yaml`
```
language: "ro"
intents:
  HassShoppingListAddItem:
    data:
      - sentences:
          - "adaug(ă|a) <item> (la|pe|<in>) <my_list>"
          - "pune <item> (pe|<in>) <my_list>"
          - "asdf <item> dsa"
        response: item_added
        expansion_rules:
          my_list: "lista [mea] de cump(ă|a)r(ă|a)turi"
          item: "{shopping_list_item:item}"
```

`sentences/ro/_common.yaml`
```
expansion_rules:
  in: "((î|i)n)"
```

And I get this:
```
@tetele ➜ /workspaces/intents (main ✗) $ python3 -m script.intentfest parse --language ro --sentence 'adauga branza topita pe lista de cumparaturi'
{
  "text": "adauga branza topita pe lista de cumparaturi",
  "match": true,
  "intent": "HassShoppingListAddItem",
  "slots": {
    "item": "branza topita branza top"
  },
  "context": {},
  "response_key": "item_added",
  "response": "Am adăugat branza topita branza top"
}
```

however, the sentence without `<in>` seems to work ok
```
@tetele ➜ /workspaces/intents (main ✗) $ python3 -m script.intentfest parse --language ro --sentence 'asdf branza topita dsa'
{
  "text": "asdf branza topita dsa",
  "match": true,
  "intent": "HassShoppingListAddItem",
  "slots": {
    "item": "branza topita "
  },
  "context": {},
  "response_key": "item_added",
  "response": "Am adăugat branza topita"
}
```

In hassil, I've added a new test file called `examples/sl.yaml` but slot recognition works there
```
language: "ro"
intents:
  HassShoppingListAddItem:
    data:
      - sentences:
          - "adaug(ă|a) <item> (la|pe|<in>) <my_list>"
          - "pune <item> (pe|<in>) <my_list>"
          - "asdf <item> dsa"
        response: item_added
        expansion_rules:
          my_list: "lista [mea] de cump(ă|a)r(ă|a)turi"
          item: "{shopping_list_item:item}"

expansion_rules:
  in: "((î|i)n)"
lists:
  shopping_list_item:
    wildcard: true
```

```
@tetele ➜ /workspaces/hassil (main ✗) $ python -m hassil examples/sl.yaml 
INFO:hassil:Area names: []
INFO:hassil:Device/Entity names: []
Reading sentences from stdin...
adauga branza topita pe lista de cumparaturi
{'intent': 'HassShoppingListAddItem', 'item': 'branza topita '}
```

More over, if I remove the `<in>` expansion rule from the sentences in the intents repo `sentences/ro/shopping_list_HassShoppingListAddItem.yaml`
```
language: "ro"
intents:
  HassShoppingListAddItem:
    data:
      - sentences:
          - "adaug(ă|a) <item> (la|pe) <my_list>"
          - "pune <item> (pe) <my_list>"
          - "asdf <item> dsa"
        response: item_added
        expansion_rules:
          my_list: "lista [mea] de cump(ă|a)r(ă|a)turi"
          item: "{shopping_list_item:item}"
```
recognition works fine
```
@tetele ➜ /workspaces/intents (main ✗) $ python3 -m script.intentfest parse --language ro --sentence 'adauga branza topita pe lista de cumparaturi'
{
  "text": "adauga branza topita pe lista de cumparaturi",
  "match": true,
  "intent": "HassShoppingListAddItem",
  "slots": {
    "item": "branza topita "
  },
  "context": {},
  "response_key": "item_added",
  "response": "Am adăugat branza topita"
}
```
