### ISSUE TITLE
Can't control the lights of a room in french

### ISSUE THREAD

**Issue by thomasd-** [home-assistant/intents#1509]
Home assistant version : 2023.8.2

When using assist in french, the phrase "allumer les lumières du salon" is not understood, while the equivalent phrase in enlgish (with voice assistant configured in english) "turn on the lights in salon" is understood and executed as intended.

Playing with the developper tools show some subtle differences in how they are interpreted :

allumer les lumières du salon
Language: français (fr) 
```
intent:
  name: HassTurnOn
slots:
  area: salon
  domain: light
  name: all
details:
  area:
    name: area
    value: salon
    text: salon
  domain:
    name: domain
    value: light
    text: ''
  name:
    name: name
    value: all
    text: ''
targets: {}
```

turn on the lights in salon
Language: anglais (en) 
```
intent:
  name: HassTurnOn
slots:
  area: salon
  domain: light
details:
  area:
    name: area
    value: salon
    text: salon
  domain:
    name: domain
    value: light
    text: ''
targets:
  light.lumieres_ecran:
    matched: true
  light.lumieres_du_canape:
    matched: true
```

As you can see, in french, no target is found for the action while in english my two lights are found.
The only other difference I see is that the french adds a "name: all" entry in the slots.

Thanks
