### ISSUE TITLE
FAILED tests/test_language_sentences.py::test_light_HassLightSet[sl] - AssertionError: Recognition failed 

### ISSUE THREAD

**Issue by andrejs2** [home-assistant/intents#1580]
Hi!

I've been banging my head with this error yesterday and today already for few hours, bat can't figure out the cause.
Since the translation and structure derived from Croatian file, I would kindly ask @spuljko for some help if I may :) 

My sentence file `light_HassLightSet.yaml`:
```

language: sl
intents:
  HassLightSet:
    data:
      - sentences:
          - <spremeni> <name> na <brightness>
          - <spremeni> [jakost|svetlost] [luč] [v|na] <area> na [jaskosti] [moči|jakost[i]|svetlost[i]|odstotk[ov|a]|procent[ov|a]]
        response: brightness

      #- sentences:
       #   - <spremeni> [moč|jakost] [luč[ke|i|k]|osvetlitve|razsvetljave]
        #    [v|na] <area> [na] <brightness> [moči|jakosti|svetlost[i]|procent[ov|a]|odstotk[a|ov]]
       # response: brightness

      #brightness min/max
      - sentences:
          - "<spremeni> <name> na {brightness_level:brightness}"
          - "<spremeni> [osvetlitev|jakost|svetlost|svetlobo] [luč[ke|i]|svetil[ke|a]|osvetlitve|razsvetljave] [uv|na] <name> na {brightness_level:brightness} [moči|jakosti|svetlosti|osvetlitve]"
        slots:
          brightness: 100
        response: brightness

      - sentences:
          - "<spremeni> [jakost|moč] [luč[ke|i]|svetil[ke|a]|osvetlitve|razsvetljave] [v|na] <area> [na] {brightness_level:brightness} [moči|jakosti|svetlosti|osvetlitve]"
          - "<spremeni> <area> [jakost|moč] ([luč[ke|i]|svetil[ke|a]|osvetlitve|razsvetljave]) [na] {brightness_level:brightness} [moči|jakosti|svetlosti|osvetlitve]"
        slots:
          brightness: 100
        response: brightness

      # color
      - sentences:
          - <spremeni> [barvo] <name> [na|v] {color}
          - <spremeni> <name> [na|v] {color} [barvo]
        response: color

      - sentences:
          - <spremeni> [barvo] [luč[ke|i]|svetil[ke|a]|osvetlitve|razsvetljave] [v|na] <area> [na|v] {color}
          - <spremeni> [osvetlitev|jakost|svetlost|svetlobo] [v|na] <area> [na|v] {color}
          - <spremeni> [u|na] <area> [osvetlitev|jakost|svetlost|svetlobo] [na|v] {color}
        response: color
```

My test file light_HassLightSet.yaml:
```

language: sl
tests:
  #brightness
  - sentences:
      - Spremeni osvetlitev v kuhinji na 50%
      - Spremeni nočno luč na 50 odstotkov
      - Nastavi nočno lučko na 50 odstotkov
      - Nastavi nočno luč na 50 odstotkov
      - Nastavi nočno luč na 50 odstotkov
      - Spremeni nočno luč na 50 odstotkov svetlosti
      - Nastavi nočno luč na 50 jakosti
      - Povečaj nočno lučko na 50 odstotkov
    intent:
      name: HassLightSet
      slots:
        brightness: 50
        name:
          - nočno luč
          - kuhinji
          - nočno lučko
          - luč
          - lučko
          - nočno

    response: "Jakost je nastavljena"

  - sentences:
      - Nastavi jakost v spalnici na 50%
      - Spremeni moč v spalnici na 50%
      - Nastavi svetlost v spalnici na 50%
      - Povečaj svetlost v spalnici na 50%
      - Zmanjšaj jakost v spalnici na 50%
    intent:
      name: HassLightSet
      slots:
        brightness: 50
        area:
          - spalnici
    response: "Jakost je nastavljena"

  - sentences:
      - Nastavi nočno luč na rdečo
      - Nastavi nočno luč na rdečo barvo
      - Spremeni barvo nočne luči na rdečo
    intent:
      name: HassLightSet
      slots:
        color: red
        name:
          - nočno luč
          - nočne luči
    response: "Barva je nastavljena"

  - sentences:
      - Nastavi kuhinjsko razsvetlitev na redeče
      - Nastavi kuhinjska svetila na rdečo barvo
      - Nastavi svetila v kuhinji na rdeče
    intent:
      name: HassLightSet
      slots:
        color: red
        area:
          - kuhinji
          - kuhinjska
          - kuhinjsko
    response: "Barva je nastavljena"

  - sentences:
      - Nastavi barvo svetila v dnevni sobi na modro
      - Nastavi barvo dnevne sobe na modro
    intent:
      name: HassLightSet
      slots:
        color: blue
        area:
          - dnevni sobi
          - dnevne sobe
    response: "Barva je nastavljena"

  - sentences:
      - Nastavi nočno luč na najmočnejšo
      - Nastavi svetlost nočne lučke na maksimalno
      - Spremeni nočno svetilko na maksimalno osvetlitev
    intent:
      name: HassLightSet
      slots:
        brightness: 100
        name:
          - nočno luč
          - nočne lučke
          - nočno svetilko
    response: "Jakost je nastavljena"

  - sentences:
      - Nastavi luč v spalnici na maksimum
      - Spremeni jakost luči v spalnici na najmočnejše
    intent:
      name: HassLightSet
      slots:
        brightness: 100
        area:
          - spalnici
    response: "Jakost je nastavljena"

  - sentences:
      - Nastavi kuhinjsko luč na maksimum
    intent:
      name: HassLightSet
      slots:
        brightness: 100
        area:
          - kuhinjsko
    response: "Jakost je nastavljena"

  - sentences:
      - Spremeni nočno luč na 50%
    intent:
      name: HassLightSet
      slots:
        brightness: 1
        name:
          - nočno lučko
    response: "Jakost je nastavljena"
```

and this is the output of `test`:
```

Running tests for file light_HassLightSet.yaml

Language: sl
[WARN] responses/sl/HassTurnOn.yaml: unused response default
[WARN] responses/sl/HassTurnOn.yaml: unused response lock
[WARN] responses/sl/HassTurnOn.yaml: unused response scene
[WARN] responses/sl/HassTurnOn.yaml: unused response script
[WARN] responses/sl/HassTurnOff.yaml: unused response default
[WARN] responses/sl/HassTurnOff.yaml: unused response lock
[WARN] responses/sl/HassGetState.yaml: unused response default

All good!
=================================================== test session starts ===================================================
platform linux -- Python 3.10.12, pytest-7.3.1, pluggy-1.0.0 -- /usr/local/py-utils/venvs/pytest/bin/python
cachedir: .pytest_cache
rootdir: /workspaces/intents
configfile: pyproject.toml
testpaths: tests
collected 45 items / 43 deselected / 2 selected                                                                           

tests/test_language_intents.py::test_light_HassLightSet[sl] PASSED                                                  [ 50%]
tests/test_language_sentences.py::test_light_HassLightSet[sl] FAILED                                                [100%]

======================================================== FAILURES =========================================================
_______________________________________________ test_light_HassLightSet[sl] _______________________________________________

language = 'sl'
intent_schemas = {'HassClimateGetTemperature': {'description': 'Gets the current temperature of a climate device or entity', 'domain': ...'required': False}, 'name': {'description': 'Name of a device or entity', 'required': False}}, 'supported': True}, ...}
slot_lists = {'area': TextSlotList(values=[TextSlotValue(text_in=TextChunk(text='spalnici', original_text='spalnici'), value_out='s...text='posesaj kuhinjo', original_text='posesaj kuhinjo'), value_out='posesaj kuhinjo', context={'domain': 'script'})])}
states = [State(entity_id='light.bedroom_lamp', name='nočna svetilka', hass_state='off', attributes={}, area_id='bedroom', huma...ate='on', attributes={}, area_id='living_room', human_state=None, aliases={'lestence', 'lestenca'}, _domain=None), ...]
areas = [AreaEntry(id='bedroom', name='spalnici', aliases={'spalnica'}), AreaEntry(id='garage', name='garaža', aliases={'garaž...', name='terasa', aliases={'terasi', 'teraso'}), AreaEntry(id='closet', name='omara', aliases={'omari', 'omaro'}), ...]
language_sentences = Intents(language='sl', intents={'HassClimateGetTemperature': Intent(name='HassClimateGetTemperature', data=[IntentData...avo|svetilk[e|o]')}, skip_words=['prosim', 'takoj', 'lahko', 'daj'], settings=IntentsSettings(ignore_whitespace=False))
language_responses = {'HassClimateGetTemperature': {'default': '{{ state.state }} degrees'}, 'HassClimateSetTemperature': {'default': 'Temp...h }}\n', ...}, 'HassLightSet': {'brightness': 'Jakost luči je nastavljena', 'color': 'Barva luči je nastavljena'}, ...}

    def test_func(
        language: str,
        intent_schemas: dict[str, Any],
        slot_lists: dict[str, SlotList],
        states: List[State],
        areas: List[AreaEntry],
        language_sentences: Intents,
        language_responses: dict[str, Any],
    ) -> None:
>       do_test_language_sentences_file(
            language,
            test_file.stem,
            intent_schemas,
            slot_lists,
            states,
            areas,
            language_sentences,
            language_responses,
        )

tests/test_language_sentences.py:199: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

language = 'sl', test_file = 'light_HassLightSet'
intent_schemas = {'HassClimateGetTemperature': {'description': 'Gets the current temperature of a climate device or entity', 'domain': ...'required': False}, 'name': {'description': 'Name of a device or entity', 'required': False}}, 'supported': True}, ...}
slot_lists = {'area': TextSlotList(values=[TextSlotValue(text_in=TextChunk(text='spalnici', original_text='spalnici'), value_out='s...text='posesaj kuhinjo', original_text='posesaj kuhinjo'), value_out='posesaj kuhinjo', context={'domain': 'script'})])}
states = [State(entity_id='light.bedroom_lamp', name='nočna svetilka', hass_state='off', attributes={}, area_id='bedroom', huma...ate='on', attributes={}, area_id='living_room', human_state=None, aliases={'lestence', 'lestenca'}, _domain=None), ...]
areas = [AreaEntry(id='bedroom', name='spalnici', aliases={'spalnica'}), AreaEntry(id='garage', name='garaža', aliases={'garaž...', name='terasa', aliases={'terasi', 'teraso'}), AreaEntry(id='closet', name='omara', aliases={'omari', 'omaro'}), ...]
language_sentences = Intents(language='sl', intents={'HassClimateGetTemperature': Intent(name='HassClimateGetTemperature', data=[IntentData...avo|svetilk[e|o]')}, skip_words=['prosim', 'takoj', 'lahko', 'daj'], settings=IntentsSettings(ignore_whitespace=False))
language_responses = {'HassClimateGetTemperature': {'default': '{{ state.state }} degrees'}, 'HassClimateSetTemperature': {'default': 'Temp...h }}\n', ...}, 'HassLightSet': {'brightness': 'Jakost luči je nastavljena', 'color': 'Barva luči je nastavljena'}, ...}

    def do_test_language_sentences_file(
        language: str,
        test_file: str,
        intent_schemas: dict[str, Any],
        slot_lists: dict[str, SlotList],
        states: List[State],
        areas: List[AreaEntry],
        language_sentences: Intents,
        language_responses: dict[str, Any],
    ) -> None:
        """Tests recognition all of the test sentences for a language"""
        if not get_test_path(language, test_file).exists():
            return
    
        testing_domain, testing_intent = test_file.rsplit("_", maxsplit=1)
    
        seen_sentences = set()
        template_env = Environment(loader=BaseLoader())
    
        for test in load_test(language, test_file)["tests"]:
            intent = test["intent"]
            assert (
                intent["name"] == testing_intent
            ), f"File {test_file}: Unexpected intent {intent['name']}. Only test for intent {testing_intent}"
    
            if not test["sentences"]:
                continue
    
            if testing_domain != "homeassistant":
                # Domain specific files (ie light_HassTurnOn.yaml) should only test
                # sentences for the light domain.
                if intent_schemas[testing_intent]["domain"] == testing_domain:
                    assert ("domain" not in intent.get("slots", {})) and (
                        "domain" not in intent.get("context", {})
                    ), f"File {test_file}: tests should not have a domain slot"
                else:
                    assert (intent.get("slots", {}).get("domain") == testing_domain) or (
                        intent.get("context", {}).get("domain") == testing_domain
                    ), f"File {test_file}: tests should have domain slot set to {testing_domain}"
    
            intent_context = intent.get("context", {})
            expected_response_texts = test.get("response")
            if expected_response_texts:
                if isinstance(expected_response_texts, str):
                    expected_response_texts = {expected_response_texts}
                else:
                    expected_response_texts = set(expected_response_texts)
    
            for sentence in test["sentences"]:
                assert (
                    sentence not in seen_sentences
                ), f"Duplicate sentence found: {sentence}"
                seen_sentences.add(sentence)
    
                result = recognize(
                    sentence,
                    language_sentences,
                    slot_lists=slot_lists,
                    intent_context=intent_context,
                )
>               assert result is not None, f"Recognition failed for '{sentence}'"
E               AssertionError: Recognition failed for 'Spremeni osvetlitev v kuhinji na 50%'
E               assert None is not None

tests/test_language_sentences.py:108: AssertionError
================================================= short test summary info =================================================
FAILED tests/test_language_sentences.py::test_light_HassLightSet[sl] - AssertionError: Recognition failed for 'Spremeni osvetlitev v kuhinji na 50%'
```
