### ISSUE TITLE
[ES] Unable to make some combinations on shopping list

### ISSUE THREAD

**Issue by arpia49** [home-assistant/intents#1602]
Hello, I'm unable to make the following sentences work:

- Añadir manzanas a la lista de la compra
- Añadir manzanas a mi lista de la compra

![image](https://github.com/home-assistant/intents/assets/126833/7a6a2d7d-dfc8-4a99-92c6-a3329649b7fa)

While the following works fine:

- Añadir manzanas en la lista de la compra
- Añadir manzanas en mi lista de la compra

![image](https://github.com/home-assistant/intents/assets/126833/ebf2c465-0d20-4bfd-82c3-198a4f04485d)

@davefx  I think something may be wrong in the definition, maybe spacing?

[sentences/es/shopping_list_HassShoppingListAddItem.yaml](https://github.com/home-assistant/intents/blob/main/sentences/es/shopping_list_HassShoppingListAddItem.yaml)

**Comment by luca-angemi** [comment]
Having the same issue, I think the problem is because of this

![image](https://github.com/home-assistant/intents/assets/9977955/1c395648-5c42-4877-98ea-2ff867500f3b)

so basically

```
    data:
      - sentences:
          - <añadir> <item> (en|a)<my_list>
        response: item_added
        expansion_rules:
          my_list: "[ mi| la] lista [de] [la] [compra]"
```

HA gets **```manzas a l```** as ```<item>``` then **```a```** as ```(a)``` then **```lista de la compra```** as ```<my_list>```.

To workaround this I extended the intent:

```
language: "es"
intents:
  HassShoppingListAddItem:
    data:
      - sentences:
          - "apunta {shopping_list_item:item}."
        response: item_added
```

With this I just have to say **```apunta manzanas.```**

To be noticed that the final ```.``` avoids having in your list ```manzanas.```
