### ISSUE TITLE
[FR] features area awareness

### ISSUE THREAD

**Issue by chpego** [home-assistant/intents#1815]
![image](https://github.com/home-assistant/intents/assets/38792705/1dd68ce5-c7e9-4e10-b21f-784d4ea39d23)

Impossible to use the feature introduced in Year of the Voice - Chapter 5 (Area awareness), only available in EN/NL, but not for french users.
Intent files seem to be missing the necessary elements

I tried to do it with custom intents by looking at the PR #1632 and #1776 , but it doesn't work.

my code:
````
---
# Example config/custom_sentences/fr/test.yaml
language: "fr"
intents:
  HassTurnOn:
    data:
      - sentences:
          - "<allume> [la] [les] (<lumiere> | <lumieres>) [ici]"
        slots:
          domain: light
        response: "lights_area"
        requires_context:
          area: "null"
  HassTurnOff:
    data:
      - sentences:
          - "<eteins> [la] [les] (<lumiere> | <lumieres>) [ici]"
        slots:
          domain: light
        response: "lights_area"
        requires_context:
          area: null
````
