### ISSUE TITLE
[HU] Simple turn on sentences were removed from the default turn on, please revert it to the original state

### ISSUE THREAD

**Issue by lajoshanko** [home-assistant/intents#1944]
Sentences like “<name> be” were used by the whole family, now they ceased to work due to the recent changes in the default turn on intent. Please revert it to the original state as it is a breakong change to the family.

**Comment by lajoshanko** [comment]
Just checked the root cause and I think the excluded context lights is also problematic, but it might be necessary for the new error handling.

**Comment by v1k70rk4** [comment]
Okay, I'll add the words "be" and "bekapcsol[ás]" to the <turn_on> function and "ki"  and "kikapcsol[ás]" to the <turn_off>
Unfortunately, however, it will only be included in the next major version. :(
I aimed for the live speech, but I understand the problem.

**Comment by v1k70rk4** [comment]
I guess I don't see how the be / ki worked. 

This was the original:
```
HassTurnOn:
data:
- sentences:
- <name> <turn_on>

``` 

``` 
 turn_on: "[kapcsol | kapcsold | kapcsolj | nyisd] (be|fel|föl)[kapcsol][ás]"
 turn_off: "[kapcsol | kapcsold | kapcsolj | zárd | oltsd] (ki|le|el)[kapcsol][ás]"
```

current version (the semicolon signifies free word order)
```
  HassTurnOn:
    data:
      - sentences:
          - "(<turn_on>;<area>;<name>)"
          - "(<turn_on>;<name>)"
        excludes_context:
          domain:
            - binary_sensor
            - cover
            - lock
            - scene
            - script
            - sensor
            - light
```
 
```
  turn_on: "(kapcsol[d|j] (be|fel|föl)|(be|fel|föl)kapcsol[ás]|oltsd (fel|föl))"
  turn_off: "((kapcsol[d|j] (ki|le))|(ki|le)kapcsol[ás]|oltsd (el|le))"
```

It seemingly should work with "<name>be" and so far "<name> ki" hasn't worked either.

https://github.com/home-assistant/intents/discussions/368
You can write any idea here and we'll include it if it fits with the extended version. Unfortunately, since it can do a lot, we need to make sure that the sentences don't conflict.

Additionally, there is a bug that could still cause problems: https://github.com/home-assistant/core/issues/109868
