### ISSUE TITLE
In the case of covers, the "which" / "how many" questions do not work.

### ISSUE THREAD

**Issue by v1k70rk4** [home-assistant/intents#1948]
Hello, I noticed something that I think used to work:
If I ask whether the living room door is open, I get a correct answer that it is.
But if I ask how many doors are open, it says 0 and it's as if it doesn't see a single door at all.
The question seems to be language-independent because I get a similar result in English as well.

Q: A nappali ajtó nyitva van? [living room door is open]  R: yes 
```
intent:
  name: HassGetState
slots:
  name: nappali ajtó
  state: nyitva
  domain: binary_sensor
  device_class: door
details:
  name:
    name: name
    value: Nappali ajtó
    text: nappali ajtó
  state:
    name: state
    value: 'on'
    text: nyitva
  domain:
    name: domain
    value: binary_sensor
    text: ''
  device_class:
    name: device_class
    value: door
    text: ''
targets:
  binary_sensor.nyitaserzekelo_nappali_ajto_contact:
    matched: true
match: true
sentence_template: <name> {bs_door_states:state} van [<area>]
unmatched_slots: {}
source: builtin
```
Q:  Hány ajtó van nyitva? [ how many doors are open]  R: 0
It shows here that there are no targets even though there are 3 doors that I am monitoring.
```
intent:
  name: HassGetState
slots:
  device_class: ajtó
  state: nyitva
  domain: cover
details:
  device_class:
    name: device_class
    value: door
    text: ajtó
  state:
    name: state
    value: open
    text: nyitva
  domain:
    name: domain
    value: cover
    text: ''
targets: {}
match: true
sentence_template: <mennyi> {cover_classes:device_class} van {cover_states:state} [<area>]
unmatched_slots: {}
source: builtin
```
