### ISSUE TITLE
Assist is not able to set Thermostat Temperatures

### ISSUE THREAD

**Issue by jannis3005** [home-assistant/intents#1982]
I cannot get the HassClimateSetTemperature Intent to work for me (running on 2024.2 ), neither in German nor English.
Checking using the debug tools and some of the test sentences I can see, that it always recognizes different intents:

Examples:

1. English [English Test Sentences](https://github.com/home-assistant/intents/blob/main/tests/en/climate_HassClimateSetTemperature.yaml):

set temperature to 30° => HassLightSet
set temperature to 30° C => HassLightSet
set bedroom temp to 50 degrees Fahrenheit => HassLightSet

2. German [German Test Sentences]():

Stelle im Wohnzimmer die Temperatur auf 30 Grad Celsius => HassListAddItem
Stelle die Temperatur auf 20 Grad Celsius => HassListAddItem
Setze die Temperatur vom Wohnzimmerthermostat auf 25 °C => HassListAddItem

Looking at the [Intens](https://github.com/home-assistant/intents/blob/main/sentences/de/climate_HassClimateSetTemperature.yaml):

`<setzen> [<area>] <artikel> Temperatur auf <temperature> `
should match
`Stelle im Wohnzimmer die Temperatur auf 30 Grad Celsius`

However, it detects 'stelle im wohnzimmer die temperatur' as item and then it does not find a list called 30 Grad Celsius
<item> (auf|in) <meine_liste> [setzen|schreiben|nehmen]

Here's the output from dev tools:

```yaml
intent:
  name: HassListAddItem
slots:
  item: 'stelle im wohnzimmer die temperatur '
details:
  item:
    name: item
    value: 'stelle im wohnzimmer die temperatur '
    text: 'stelle im wohnzimmer die temperatur '
targets: {}
match: false
sentence_template: <item> (auf|in) <meine_liste> [setzen|schreiben|nehmen]
unmatched_slots:
  name: 30 grad celsius
source: builtin
```
