### ISSUE TITLE
[ES] HassShoppingListAddItem chops mid-sentence

### ISSUE THREAD

**Issue by cibernox** [home-assistant/intents#2053]
I tried to reproduce adding an example to the tests, but somehow my example seems to work when using the test harness, but it fails un 2024.2 and 2023.3, released mere hours ago.

The sentence `Añade pepinillos a la lista` it's recognized as:
```
intent:
  name: HassShoppingListAddItem
slots:
  item: pepinillos a l
details:
  item:
    name: item
    value: pepinillos a l
    text: pepinillos a l
targets: {}
match: true
sentence_template: <añadir> <item> <my_list>
unmatched_slots: {}
source: builtin
```

So I end up with an item named "pepinillos a l" in the shopping list.

I did try to understand why this could be happening based on the pattern:
```
      - sentences:
          - <añadir> <item> <my_list>
        response: item_added
        expansion_rules:
          my_list: "(en|a) [mi|la] lista [de] [la] [compra]"
          item: "{shopping_list_item:item}"
```
But honestly I can see anything wrong at first glance, unless it's a whitespace thing.
