### ISSUE TITLE
2024.06  update has damaged some functions of custom sentences

### ISSUE THREAD

**Issue by mitrokun** [home-assistant/intents#2212]
After the 2024.06 update, my custom sentences stopped accepting the alias of the area.  
And in intent_script, the area_name(area) construction began to give the value None.

Use this code (simple sentence and a intent script ) to check if you have same problem.
```
  tempstat:
    data:
      - sentences:
          - "Tell me the temperature in the {area}"

tempstat:
  action:
    []
  speech:
    text: "temperature in the {{ area_name(area) }} {{  states.sensor|selectattr('attributes.device_class', 'eq', 'temperature')|selectattr('entity_id', 'in', area_entities(area))|map(attribute='state')|min|int  }}" 
```
With built-in intent, aliases work
