### ISSUE TITLE
[de] HassLightSet with satellite area

### ISSUE THREAD

**Issue by joie96** [home-assistant/intents#2237]
To set the brightness in the area of the activated satellite does not work.

I think it should be something like this:

```
language: de
intents:
  HassLightSet:
    data:
      # Change brightness of all lights in the same area as a satellite device
      - sentences:
          - "<setzen>[ <artikel>] Helligkeit[ auf] <brightness>"
          - "[<artikel> ]Helligkeit[ auf] <brightness>[ <setzen>]"
          - "dimme[ <artikel> Helligkeit][ (auf|zu)] <brightness>"
          - "[Helligkeit][ (auf|zu)] <brightness> dimmen"
        response: "brightness"
        requires_context:
          area:
            slot: true
```

But even when I'm using this in custom_sentences to extend the build in HassLightSet, this is conflicting with the current 
`- "[<setzen> ]<artikel> Helligkeit[ (<lichter>|<alle_lichter>)][ <area>][ auf] <brightness>[ ein]"`
([https://github.com/home-)assistant/intents/blob/main/sentences/de/light_HassLightSet.yaml#L15](url))

I think the above sentence needs to be changed, because without all optional parts it reduces to 
`- "Helligkeit <brightness>"`
which I think does not make sense without
```
        requires_context:
          area:
            slot: true
```

**Comment by mitrokun** [comment]
for custom sentence, you need to create your own intent and script.

This example works:
```
language: de
intents:
  BrightnessSet:
    data:
      - sentences:
          - "Helligkeit <brightness>"
        requires_context:
          area:
            slot: true

BrightnessSet:
  action:
    service: light.turn_on
    data:
      brightness_pct: "{{brightness}}"
    target:
      area_id: "{{ area_id(area) }}"
  speech:
    text: "Ok"
```
