### ISSUE TITLE
[pl] Climate not working

### ISSUE THREAD

**Issue by Mis1ify** [home-assistant/intents#2384]
It seems like if I want to set a temperature on a climate, Assist thinks I want to change the light color, not the temperature.

`intent:
  name: HassLightSet
slots: {}
details: {}
targets: {}
match: false
sentence_template: <set> <name> na {color} [kolor]
unmatched_slots:
  name: 'temperaturę '
  color: 30° celsjusza
source: builtin`

**Comment by witold-gren** [comment]
Can you add more information how you name your devices and how looks your sentences? If you go to test case in polish language you can find more examples how you can use it. https://github.com/home-assistant/intents/blob/main/tests/pl/climate_HassClimateSetTemperature.yaml

**Comment by Mis1ify** [comment]
Yes I use this file as an example, and it still doesn't understand me. No matter what sentence from that file I say, it searches for the light, not the climate.

**Comment by witold-gren** [comment]
I checked it in my instances using `Sentences parser` and you're right.. in my case they return:
```
intent:
  name: HassLightSet
slots: {}
details: {}
targets: {}
match: false
sentence_template: <set> <name> na {color} [kolor]
unmatched_slots:
  name: 'temperaturę '
  color: 30 stopni
source: builtin
```
but it should return `HassClimateSetTemperature`. I will look on it..
