### ISSUE TITLE
[de] Problem while switching entites in areas

### ISSUE THREAD

**Issue by M0P** [home-assistant/intents#2775]
I have a problem with sentence recognition in German. I am trying to turn on a device (type: switch) in a specific area. When I use English, everything works fine. However, when I use German, the wrong sentence_template is used as soon as I include an area.

Example sentence in German: “Schalte die Kamera im Garten an” (English: Turn on the camera in the garden)
The entity I want to trigger has an alias “Kamera”. "Garten" is an area.

When I use it without the area, it works as long as the entity name is unique.

```intent:
  name: HassTurnOn
slots:
  area: Garten
  domain: scene
details:
  area:
    name: area
    value: Garten
    text: Garten
  domain:
    name: domain
    value: scene
    text: ''
targets: {}
match: false
sentence_template: '[<szene> ]<name> <area>[ (<aktivieren>|<ausfuehren>|<an>)]'
unmatched_slots:
  name: 'Schalte die Kamera '
source: builtin```

**Comment by Jeinhaus** [comment]
It's the same for me. Using only the area or only the alias for e.g. a light works, but using an alias combined with an area does not.

Here the entitie's alias is `Deckenlampe` in the area `Wohnzimmer`:

**Schalte die Deckenlampe im Wohnzimmer aus**
```
intent:
  name: HassTurnOn
slots:
  domain: scene
details:
  domain:
    name: domain
    value: scene
    text: ''
targets: {}
match: false
sentence_template: '[<szene> ]<name> <area>[ (<aktivieren>|<ausfuehren>|<an>)]'
unmatched_slots:
  name: 'Schalte '
  area: Deckenlampe im Wohnzimmer aus
source: builtin
```

If I only use the area or the alias (if unique) it works as expected: 

**Schalte Deckenlampe ein**
```
intent:
  name: HassTurnOn
slots:
  name: Deckenlampe
details:
  name:
    name: name
    value: Deckenlampe
    text: Deckenlampe
targets: {}
match: true
sentence_template: (<schalten>|<machen>) <name> <an>
unmatched_slots: {}
source: builtin
```

**Schalte Licht im Wohnzimmer an**
```
intent:
  name: HassTurnOn
slots:
  area: Wohnzimmer
  domain: light
details:
  area:
    name: area
    value: Wohnzimmer
    text: Wohnzimmer
  domain:
    name: domain
    value: light
    text: ''
targets:
  light.gemutliche_lichter:
    matched: true
  light.steckdose_lampe_wohnzimmer:
    matched: true
  light.ecklampe_wohnzimmer:
    matched: true
  light.leds_upkammer:
    matched: true
  light.lampe_wohnzimmer:
    matched: true
match: true
sentence_template: <schalten> (<licht>|<lichter>|<alle_lichter>) <area> <an>
unmatched_slots: {}
source: builtin
```
