### ISSUE TITLE
[en] skip word "i want" limitation when creating custom sentences

### ISSUE THREAD

**Issue by garyt72** [home-assistant/intents#2795]
When creating custom sentences, there is no indication that a skip word is preventing the custom sentence from matching.  Example provided below.

custom_sentences/en/WatchTV.yaml:
```yaml
language: en
intents:
  WatchTv:
    data:
      - sentences:
          - i want to watch tv                # this doesn't work
          - (i'm | i am) going to watch tv    # this does work
```

Debug showing that the sentence is identical but does not match.
![image](https://github.com/user-attachments/assets/55e9c8c7-c9a5-4cad-ab9f-2861b24955a6)

Would be helpful if any or all of the following could be done:

- provide an option to override/ignore skip words from intents/sentences/xx/_common.yaml 
- show additional information in debug window when the text is altered by the following for example
    - a skip word is used/triggered/ignored
    - a conversion is performed due to a list in/out value
