### ISSUE TITLE
[DE] Device in Area triggers scene instead of generic HassTurnOn

### ISSUE THREAD

**Issue by badewanne1234** [home-assistant/intents#2875]
I have a light called "Garderobe" and an area "Eingang", of course the light is linked to the area.

When parsing the sentence "Schalte Garderobe in Eingang ein" or "Schalte Garderobe in Eingang an" in the dev tools, I would expect it to parse it as follows:

```
intent:
  name: HassTurnOn
slots:
  area: Eingang
  name: Garderobe
details:
  area:
    name: area
    value: Eingang
    text: Eingang
  name:
    name: name
    value: Garderobe
    text: garderobe
targets:
  light.licht_garderobe:
    matched: true
match: true
sentence_template: ' (<schalten>|<machen>) <name>[ <area>] <an>'
unmatched_slots:
  name:{}
source: builtin
```

Instead, its parsed as a scene

```
intent:
  name: HassTurnOn
slots:
  area: Eingang
  domain: scene
details:
  area:
    name: area
    value: Eingang
    text: Eingang
  domain:
    name: domain
    value: scene
    text: ''
targets: {}
match: false
sentence_template: '[<szene> ]<name> <area>[ (<aktivieren>|<ausfuehren>|<an>)]'
unmatched_slots:
  name: 'Schalte Garderobe '
source: builtin
```

I'm not sure why it parses as a scene, any thoughts?

**Comment by badewanne1234** [comment]
You are correct, I was on 2024.12.x, I updated to 2025.1.2 now and its a goner. Thank you, sorry for bothering...

**Comment by amatthies** [comment]
Hm, I'm on 2025.1.4 and I have a similar problem with Home Assistant Cloud

"Licht im Schlafzimmer aus" works as expected:

```
intent:
  name: HassTurnOff
slots:
  name: Licht
  area: Schlafzimmer
details:
  name:
    name: name
    value: Licht
    text: Licht
  area:
    name: area
    value: Schlafzimmer
    text: Schlafzimmer
targets:
  light.schlafzimmer:
    matched: true
match: true
sentence_template: <name>[ <area>] <aus>[<schalten>|<machen>]
unmatched_slots: {}
source: builtin
```
but "Licht im Schlafzimmer an" wants a scene (that I don't have) and fails:

```
intent:
  name: HassTurnOn
slots:
  name: Licht
  area: Schlafzimmer
  domain: scene
details:
  name:
    name: name
    value: Licht
    text: Licht
  area:
    name: area
    value: Schlafzimmer
    text: Schlafzimmer
  domain:
    name: domain
    value: scene
    text: ''
targets: {}
match: true
sentence_template: '[<szene> ]<name> <area>[ (<aktivieren>|<ausfuehren>|<an>)]'
unmatched_slots: {}
source: builtin
```
