### ISSUE TITLE
[IT] Add radiator specific terms in climate domain

### ISSUE THREAD

**Issue by giobber** [home-assistant/intents#3055]
Hi, maybe this is a very specific scenario, but with the improvements in smart valve maybe it's worth a shot

I have several smart valves (usually a smart switch + an electric valve) registered in Home Assistant as generic thermostat. I find really inconvenient (in particular when assist is used by my parents) to call `condizionatore` o `aria condizionata` what is effectively a `termosifone` or `termo`

It's possible to add terms like `radiatore`, `termosifone`, `termo` or `riscaldamento` to the climate domain common names?

---

For now I've solved by customizing my local `_common.yaml` but I think it's more intuitive to have these options by default for a newcomer

I'll leave my actual local code if someone else is struggling to customize their intents
Create a file `config/custom_sentences/it/_common.yaml` (create subfolders if they don't exists) and add this text:
```yaml
language: it
expansion_rules:
  climate: "(clima|climatizzator(e|i)|condizionator(e|i)|aria condizionata|radiator(e|i)|termosifon(e|i)|riscaldamento|termo)"
```
As I understand this will overwrite the default climate pattern by adding the new terms
