### ISSUE TITLE
Missing an option for capturing area prepositions

### ISSUE THREAD

**Issue by jose1711** [home-assistant/intents#3100]
There does not seem to be a way to
- name areas in their basic form (`living room`, `kitchen`, `terrace`)
- capture the preposition used with area name (`[in|on|at]`) and correctly reflect the form used by the user in response.

This approach seems to do the job:

```yaml
-- common.yaml
expansion_rules:
  area: "[{area_prepositions:preposition}] {area}"
lists:
  area_prepositions:
    values:
      - in
      - on
      - at
```
```yaml
-- fixtures.yaml
areas:
  - name: "kitchen"
    id: kitchen
  - name: "living room"
    id: living_room
  - name: "terrace"
    id: terrace
```
```yaml
-- responses/..
intents:
  ..
    default: "Doing something {{ slots.preposition | default() }} {{ slots.area }}"
```

When testing with `parse --sentence` the sentence is correctly interpreted, slots are set as follows:
```json
{
  "slots": {
    "device_class": "light",
    "preposition": "on",
    "area": "terrace",
    "domain": "light"
  },
  "response": "Doing something on terrace",
```

The problem here is that this will not pass the tests:
```
AssertionError: Intent xyz does not support slot 'preposition'. See intents.yaml for supported slots
```
Overall I am missing a way to capture a piece of text (similar to regex groups) and then use it in responses.
