### ISSUE TITLE
Sample sentences do not respect entity's domain/device_class

### ISSUE THREAD

**Issue by jose1711** [home-assistant/intents#3102]
Command such as
```sh
python3 -m script.intentfest sample --language en --intents HassLightSet
```
generates sentences disregarding the domain/device_class of the entity. Example:
```
{"intent": "HassLightSet", "text": "set the Powerwall stored energy brightness to 48%"}
```
`Powerwall stored energy` is a sensor classified as `energy_storage`:
```yaml
  - name: "Powerwall stored energy"
    id: "sensor.powerwall_stored_energy"
    state: "6"
    attributes:
      device_class: energy_storage
      unit_of_measurement: "kWh"
```
and the generate action would be ignored:
```sh
$ python3 -m script.intentfest parse --language en --sentence 'set the Powerwall stored energy brightness to 48%'
$ (empty output)
```
