### ISSUE TITLE
[HU] Invalid states for cover.* entities in _fixtures.yaml

### ISSUE THREAD

**Issue by jose1711** [home-assistant/intents#3106]
As per https://www.home-assistant.io/integrations/cover/ "close" is not a supported state for an entity in cover domain. Several such entities exist in `tests/hu/_fixtures.yaml`, e. g. :

```yaml
  - name: "háló függöny"
    id: "cover.nappali_balfuggony"
    area: living_room
    state: close
```

@nagyrobi @v1k70rk4
