### ISSUE TITLE
[FR] Turn on/off lights intent not found in singular form

### ISSUE THREAD

**Issue by slegars56** [home-assistant/intents#3125]
Homeassistant core 2025.4.0

When saying "Allume la lumière dans la chambre" ou "Allume la lumière" (i.e. with context awareness), the intent for turning on the light isn't found. 
When saying "Allume les lumières..." it's found.
I don't understand why:

Sentence form /fr folder:

```
          # Allume la lumiere du bureau
          - "<allume> [<tous>] [<le>]<lumiere> [<dans>] [<le>]{area}"
```

<le> and <lumiere> are taking both, singular and plural, into account in _common.yaml:

```
  le: (le |la |les |l')
  lumiere: "(lumière[s]|lampe[s]|ampoule[s]|éclairage[s])"
```

The same issue occurs with "Eteins la lumière..."

Debug with singular:

```
 - type: intent-start
    data:
      engine: conversation.home_assistant
      language: fr
      intent_input: Éteins la lumière de la chambre
      conversation_id: 01JRBBHA0HJ196WM95W76Q2X5C
      device_id: null
      prefer_local_intents: false
    timestamp: "2025-04-08T18:45:45.457499+00:00"
  - type: intent-end
    data:
      processed_locally: true
      intent_output:
        response:
          speech:
            plain:
              speech: Désolé, je n'ai pas compris
              extra_data: null
          card: {}
          language: fr
          response_type: error
          data:
            code: no_valid_targets
        conversation_id: 01JRBBHA0HJ196WM95W76Q2X5C
        continue_conversation: false
    timestamp: "2025-04-08T18:45:45.497453+00:00"
  - type: run-end
    data: null
    timestamp: "2025-04-08T18:45:45.497498+00:00"
intent:
  engine: conversation.home_assistant
  language: fr
  intent_input: Éteins la lumière de la chambre
  conversation_id: 01JRBBHA0HJ196WM95W76Q2X5C
  device_id: null
  prefer_local_intents: false
  done: true
  processed_locally: true
  intent_output:
    response:
      speech:
        plain:
          speech: Désolé, je n'ai pas compris
          extra_data: null
      card: {}
      language: fr
      response_type: error
      data:
        code: no_valid_targets
    conversation_id: 01JRBBHA0HJ196WM95W76Q2X5C
    continue_conversation: false
```

debug with plural
```
 - type: intent-end
    data:
      processed_locally: true
      intent_output:
        response:
          speech:
            plain:
              speech: Éteint
              extra_data: null
          card: {}
          language: fr
          response_type: action_done
          data:
            targets: []
            success:
              - name: Chambre
                type: area
                id: chambre_parents
              - name: Led
                type: entity
                id: light.led_parents
              - name: Spot Droit
                type: entity
                id: light.spot_parents_2
              - name: Spot Gauche
                type: entity
                id: light.spot_parents_1
              - name: Plafonnier
                type: entity
                id: light.plafonnier_parents
            failed: []
        conversation_id: 01JRBC1BH8XFX0JNANWQGS1SW6
        continue_conversation: false
    timestamp: "2025-04-08T18:54:10.930608+00:00"
  - type: tts-start
    data:
      engine: tts.home_assistant_cloud
      language: fr-FR
      voice: ""
      tts_input: Éteint
    timestamp: "2025-04-08T18:54:10.930657+00:00"
  - type: tts-end
    data:
      tts_output:
        media_id: >-
          media-source://tts/tts.home_assistant_cloud?message=%C3%89teint&language=fr-FR&tts_options=%7B%22audio_output%22:%22mp3%22,%22voice%22:%22%22%7D
        token: 4PqENd4353V6K-jprntPkw.mp3
        url: /api/tts_proxy/4PqENd4353V6K-jprntPkw.mp3
        mime_type: audio/mpeg
    timestamp: "2025-04-08T18:54:10.931046+00:00"
  - type: run-end
    data: null
    timestamp: "2025-04-08T18:54:10.931066+00:00"
stt:
  engine: stt.home_assistant_cloud
  metadata:
    language: fr-FR
    format: wav
    codec: pcm
    bit_rate: 16
    sample_rate: 16000
    channel: 1
  done: true
  stt_output:
    text: Éteins les Lumières dans la Chambre.
intent:
  engine: conversation.home_assistant
  language: fr
  intent_input: Éteins les Lumières dans la Chambre.
  conversation_id: 01JRBC1BH8XFX0JNANWQGS1SW6
  device_id: null
  prefer_local_intents: false
  done: true
  processed_locally: true
  intent_output:
    response:
      speech:
        plain:
          speech: Éteint
          extra_data: null
      card: {}
      language: fr
      response_type: action_done
      data:
        targets: []
        success:
          - name: Chambre
            type: area
            id: chambre_parents
          - name: Led
            type: entity
            id: light.led_parents
          - name: Spot Droit
            type: entity
            id: light.spot_parents_2
          - name: Spot Gauche
            type: entity
            id: light.spot_parents_1
          - name: Plafonnier
            type: entity
            id: light.plafonnier_parents
        failed: []
    conversation_id: 01JRBC1BH8XFX0JNANWQGS1SW6
    continue_conversation: false
tts:
  engine: tts.home_assistant_cloud
  language: fr-FR
  voice: ""
  tts_input: Éteint
  done: true
  tts_output:
    media_id: >-
      media-source://tts/tts.home_assistant_cloud?message=%C3%89teint&language=fr-FR&tts_options=%7B%22audio_output%22:%22mp3%22,%22voice%22:%22%22%7D
    token: 4PqENd4353V6K-jprntPkw.mp3
    url: /api/tts_proxy/4PqENd4353V6K-jprntPkw.mp3
    mime_type: audio/mpeg

```
