### ISSUE TITLE
[CS] Implement homeassistant_HassGetState

### ISSUE THREAD

**Issue by jandusek4** [home-assistant/intents#3167]
Looking for implementation of https://github.com/home-assistant/intents/blob/main/sentences/cs/homeassistant_HassGetState.yaml
At least something like the following (only changed something as i do not know the syntax. Bases on EN variant.
```
      - sentences:
          - (víš|řekni mi|jaká je|<what_is>) [ [aktuální] (stav|hodnota)] <name> [<in_area_floor>]
        response: one
        excludes_context:
          domain:
            - scene
            - script
```
