### ISSUE TITLE
Can Not Remove Items From ToDo List

### ISSUE THREAD

**Issue by tommyjlong** [home-assistant/intents#3231]
System:
Installation method- Home Assistant OS
Core- 2025.6.1
Supervisor- 2025.05.5
Operating System- 15.2
Frontend- 20250531.3

1a) Can add items to a list:
How can I assist?
      add apples to shopping list
Added apples

As a check I see that "apples" have been added to the Shopping ToDo List

2a) Can not remove using:
      remove apples from shopping list
Sorry, I couldn't understand that

From DevTools>Assist
      remove apples from shopping list
No intent matched

2b) Can not remove using:
      remove apples from my shopping list
Sorry, I am not aware of any area called remove apples from

From DevTools->Assist
remove apples from my shopping list
```
intent:
  name: HassTurnOn
slots:
  domain: scene
details:
  domain:
    name: domain
    value: scene
    text: ''
targets: {}
match: false
sentence_template: '[activate] <area> <name> [scene]'
unmatched_slots:
  area: 'remove apples from '
  name: shopping list
source: builtin
```

[[Reference](https://github.com/OHF-Voice/intents/blob/main/sentences/en/shopping_list_HassShoppingListCompleteItem.yaml)]  From Built-Ins
```
language: "en"
intents:
  HassShoppingListCompleteItem:
    data:
      - sentences:
          - (check|complete|delete|remove) (off;<item>) (from|on|in) <my_list>
          - (check|complete|delete|remove) <item> (off|from|on|in) <my_list>
        response: item_completed
        expansion_rules:
          my_list: "[my|the] [shopping] list"
          item: "{shopping_list_item:item}"
```
