### ISSUE TITLE
Required context should be treated as inferred slots

### ISSUE THREAD

**Issue by tetele** [home-assistant/intents#734]
Intents are defined including `slot_combinations`, which define what entity-related pieces of information are required to define an intent.

However, if some of those pieces of information are simply required but not defined when declaring intents, tests should not fail.

Here's a failing example:

`sentences`
```
intents:
  HassTurnOn:
    data:
      - sentences:
          - "<porneste> [toate] <ventilatorul>"
        slots:
          domain: fan
        requires_context:
          area:
```

`tests`
```
  - sentences:
      - "porneste ventilatorul"
    intent:
      name: HassTurnOn
      slots:
        domain: fan
      context:
        area: kitchen
```

Result:
`FAILED tests/test_language_intents.py::test_fan_HassTurnOn[ro] - AssertionError: Slot combination not matched: intent='HassTurnOn', slots={'domain'}, sentence='<porneste> [toate] <ventilatorul>'`
