### ISSUE TITLE
Response tests

### ISSUE THREAD

**Issue by schizza** [home-assistant/intents#755]
Am I missing something or is this a issue to be focused on?

I have a sentences for managing brightness:

```
- sentences:
      - "Nastav jas lampičky v ložnici na 30 procent"
      - "Nastav jas lampičky v ložnici na 30"
      - "Ztlum jas lampičky v ložnici na 30 procent"
      - "Ztlum lampičku v ložnici na 30 procent"
     .......
   response:
      - "Jas lampičky v ložnici nastaven na 30%"
      - "Jas lampičky v ložnici nastaven na 30"
```
Running a test will trigger an error on sentence `Ztlum lampičku v ložnici na 30 procent`

AssertionError: Incorrect response for: Ztlum lampičku v ložnici na 30 procent
E                   assert 'Jas lampičku v ložnici nastaven na 30' in {'Jas lampičky v ložnici nastaven na 30', 'Jas lampičky v ložnici nastaven na 30%'}

In fact sentences are:  `Set brightness of a light` .....  and `Dim light .....`
The only response in Czech is: The brightness of the light is set to ...

So the problem is that the response `Jas **lampičku** v ložnici .....` is complete non sense as response, it should be as stated `Jas lampičky v ložnici nastaven na 30`

As in grammatic manner:   In the request sentence: `Ztlum lampičku ==set the light==` - ==**lampičku**== is in acusatvie case, but in response we need genitive case `Jas lampičky ==brightness of the light==` in all cases.

I hope it is understood, what I am willing to say? :)

Is there any workaround or is it something to be issued?

**Comment by davefx** [comment]
We cannot expect Home Assistant to be a grammar expert in all the supported languages, and know how to change the case of the substantives used as names of the user-defined devices (in your case) or to adapt the syntax gender of an adjective so it matches with the one in the device name (as in Spanish).

In Spanish I took the decision of simplifying the responses to totally circumvent the problem. Instead of saying "<device> turned-on", as turned-on would depend on the grammatical gender of <device>, "Device correctly turned on". We lose a information, but I'm afraid there's nothing else we can do.

**Comment by davefx** [comment]
Cannot you modify the sentence so it says something as "The lamp in the bedroom has now a bright of 50%", so the nominative case (supposedly, the default one) of the device name is used in responses?

**Comment by schizza** [comment]
I have an idea how to make it possible, but in depht it will be quite time consuming even for translators.
In responses we can have an option to determine right gender and/or grammar case, so in entity definition, we can provide right response with grammar correct sentence. 

 Example: 

```
      default: "{{ slots.name }} bylo zapnuto"
          - options:
               gender: ""
               case: "nominative"
               adverb: False
         
      lights_area: "Světla v {{ slots.area }} byla zapnuta"
         - options:
                gender: ""
                case: ""
                adverb: True
```

in tests:
```
tests:
  - sentences:
      - "zapni světlo v obýváku"
         - options:
             gender: ""
             case: nominative
             adverb: False
      - "zapni všechna světla v obývacím pokoji"
           - options:
               - adverb: True
  ```

in _fixtures:

```
areas:
  - name: (Obývac(í|ím) pokoj(i) | obývák(u)) 
    id: living_room
    options:
      - adverb: "obývacím pokoji"
      - nominative: "obývací pokoj"
      - gender: "not applicable in czech"
      - adverb: "obývacím pokoji"
 
entities:
  - name: (Lamp(a|y|u) | lampičk(a|y|u) | světl(o|a)) v obývacím pokoji
    id: light.bedroom_lamp
    area: bedroom
    options:
        nominative: "lampička"
        genitive: "lampičky"
        ......
        gender: " N/A in czech"
```

so the parser can pick up right gender, adjective or grammar case.

So for brightness:

```
 #brightness
  - sentences:
      - "Zvýšit lampičku v ložnici na 30."    - intent in nominative
        - options:
            case: genitive.   -- response will be in genitive

```

That might also solve problems with gender, right?

**Comment by synesthesiam** [comment]
@schizza This is something I'd like to focus on next. I think these issues are all related:

* User provides 1 name for an entity/area, but different forms of that name should also be matched
* Responses may be different depending on grammatical features of the input sentence, not just entities/areas
* Generating sample sentences from the current intents may produce non-grammatical sentences

Thanks for your suggestions to extend the syntax. I'll be starting a discussion in the next week or two to look at options.

**Comment by spuljko** [comment]
Well, this is very complex thing, but I like it.
I believe it is accusative not genitive for grammar case - most of the languages have [nominative-accusative   alignment](url). For in example in Croatian:
```
- sentences:
  - "Ugasi noćnu lampu" # "noćnu lampu" is accusative (whom or what)
      - options:
          case: "accusative"
- responses
   - "Noćna lampa je ugašena" #" "noćna lampa is nominative
```
Off course there are other cases, for example
```
- sentences:
  - "Koja je svjetlina noćne lampe" # what is the brightens of the night lamp - genitive
      - options:
        case: "genitive"
- response:
  - Svjetlina noćne lampe je 50% # night lamp brightness is 50%. response is also genitive
```
Also, it would be nice to have single and plural forms. For example:
```
- sentences:
  - Ugasi sva svjetla u kuhinji  # turn off all lights in kitchen. "kuhinji" is single dative, "svjetla" is plural accusative
  - Ugasi sva svjetla u svim sobama  # turn off all lights in all rooms. "sobama" is plural dative
  - Ugasi svjetlo u kuhinji # turn of kitchen light. "svjetlo" is single nominative
```
Other languages have different grammar rules, so it is very complex thing.
