### ISSUE TITLE
How to correctly provide values for {{ state.state }} response in HassClimateGetTemperature.yaml file?

### ISSUE THREAD

**Issue by witold-gren** [home-assistant/intents#807]
Hey, I observe that if I try to configure `default` value for `HassClimateGetTemperature` it looks like it didn't work. Below I created simple example:

response:
```
language: pl
responses:
  intents:
    HassClimateGetTemperature:
      default: 'Temperatura wynosi {{ state.state }} stopni'
```
sentence:
```
language: pl
intents:
  HassClimateGetTemperature:
    data:
      - sentences:
          - "(<what_is>|<how_many_is>) <temp> [<area>]"
        response: default
```
tests:
```
language: pl
tests:
  - sentences:
      - "Ile jest stopni na balkonie?"
    intent:
      name: "HassClimateGetTemperature"
    response: Temperatura wynosi 12 stopni
```

After that if I run the test `pytest tests --language pl` I can see this errors:
```
tests/test_language_sentences.py:170:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
tests/test_language_sentences.py:146: in do_test_language_sentences_file
    actual_response_text = response_template.render(
../../.virtualenvs/intents/lib/python3.9/site-packages/jinja2/environment.py:1301: in render
    self.environment.handle_exception()
../../.virtualenvs/intents/lib/python3.9/site-packages/jinja2/environment.py:936: in handle_exception
    raise rewrite_traceback_stack(source=source)
<template>:1: in top-level template code
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <jinja2.environment.Environment object at 0x1018fe7f0>, obj = Undefined, attribute = 'state'

    def getattr(self, obj: t.Any, attribute: str) -> t.Any:
        """Get an item or attribute of an object but prefer the attribute.
        Unlike :meth:`getitem` the attribute *must* be a string.
        """
        try:
>           return getattr(obj, attribute)
E           jinja2.exceptions.UndefinedError: 'state' is undefined

../../.virtualenvs/intents/lib/python3.9/site-packages/jinja2/environment.py:485: UndefinedError
=================================================================================================================== short test summary info ===================================================================================================================
FAILED tests/test_language_sentences.py::test_climate_HassClimateGetTemperature[pl] - jinja2.exceptions.UndefinedError: 'state' is undefined
================================================================================================================ 1 failed, 18 passed in 0.70s =================================================================================================================
```

How can I fixed it? I checked code in file `test_language_sentences.py` but it look like this is not implemented yet..
