### ISSUE TITLE
Merge slots and context in tests

### ISSUE THREAD

**Issue by tetele** [home-assistant/intents#816]
Tests are failing because some pieces of information are provided in the `context` and the tests are expecting them in the `slots`.

E.g. `sentences`
```
intents:
  HassTurnOff:
    data:
      - sentences:
          - "turn off [all] [the] fan[s]"
        slots:
          domain: fan
        requires_context:
          area:
        response: fans_area
```

`responses`
```
responses:
  intents:
    HassTurnOff:
      fans_area: "All fans turned off in {{ slots.area }}"
```

`tests`
```
tests:
  - sentences:
      - "turn off the fan"
    intent:
      name: HassTurnOff
      slots:
        domain: fan
      context:
        area: kitchen
    response: "All fans turned off in kitchen"
```

```
E                   AssertionError: Incorrect response for: turn off the fan
E                   assert 'All fans turned off in' in {'All fans turned off in kitchen'}

tests/test_language_sentences.py:157: AssertionError
==== short test summary info ====
FAILED tests/test_language_sentences.py::test_fan_HassTurnOff[ro] - AssertionError: Incorrect response for: turn off the fan
==== 1 failed, 18 passed in 6.54s ====
```
