### ISSUE TITLE
[RU] Can't recognize temperature sentences

### ISSUE THREAD

**Issue by HepoH3** [home-assistant/intents#929]
Core version: 2023.2.2

ru lang have following sentence rules for getting temperature:

_common.yaml:
```
expansion_rules:
  area: "[в|на] {area}"
  temp: "(температур(а|у)|градусов)"
```

climate_HassClimateGetTemperature.yaml
```yaml
language: "ru"
intents:
  HassClimateGetTemperature:
    data:
      - sentences:
          - "[Какая|сколько] <temp>"
          - "[Какая|сколько] <temp> <area>"
```

ru lang have following test cases which are pass (one thing is that there is workaround about areas word cases, but for now it's not the case):
```yaml
language: "ru"
tests:
  - sentences:
      - "Какая температура?"
      - "Сколько градусов?"
    intent:
      name: "HassClimateGetTemperature"
  - sentences:
      - "Сколько градусов в гостиной?"
      - "Какая температура в гостиной?"
    intent:
      name: "HassClimateGetTemperature"
      slots:
        area: "living_room"
  - sentences:
      - "Сколько градусов на кухне?"
    intent:
      name: "HassClimateGetTemperature"
      slots:
        area: "kitchen"
```

So I believe, when I ask assistant "What temperature" with words "Какая температура?" (first sentence copy-past without any expansion rule) I should get one of the termometers values or all termometers values (actually in repsonces I have `default: '{{ state.state }} degrees`, so it should be at least something), but instead get "sentence is not recognized" response. I tried to say "Какая температура в гостиная" (because of area word cases, I can't ask with "гостиной", I already checked it by turning on/off lights, but no luck.

I can't find some problem related core logs, maybe you point me in some direction?
